# Generated by Django 3.0.4 on 2020-03-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billingName',
        ),
    ]
